FROM python:3.9-slim
WORKDIR /app

# Copy requirements first
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy code
COPY config/ ./config
COPY dashboard/ ./dashboard

ENV PYTHONPATH=/app

# Explicitly call the module
CMD ["python", "-m", "streamlit", "run", "dashboard/app.py", "--server.port=8501", "--server.address=0.0.0.0"]